version: "3.7"
services:
  kaddem-api:
    image: kaddem-image
    container_name: projetkaddembackend
    restart: always
    ports:
      - 9191:9090
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3306/lazrakAmine?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lazrakAmine
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
